/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
  PredefinedButtonType,
  PredefinedGlobalSize,
} from './interface';

export namespace Components {
  interface OButton {
    /**
    * The text button is bold
    */
    'bold': boolean;
    /**
    * The button color
    */
    'color'?: Color;
    /**
    * The button enable status
    */
    'disabled': boolean;
    /**
    * The outline style
    */
    'outline': boolean;
    /**
    * The button size
    */
    'size'?: PredefinedGlobalSize;
    /**
    * The button type
    */
    'type'?: PredefinedButtonType;
  }
  interface OExpansionPanel {
    'close': () => Promise<void>;
    'disabled': boolean;
    'open': boolean;
    'toggleContent': () => Promise<void>;
    'value': number;
  }
  interface OExpansionPanels {}
}

declare global {


  interface HTMLOButtonElement extends Components.OButton, HTMLStencilElement {}
  var HTMLOButtonElement: {
    prototype: HTMLOButtonElement;
    new (): HTMLOButtonElement;
  };

  interface HTMLOExpansionPanelElement extends Components.OExpansionPanel, HTMLStencilElement {}
  var HTMLOExpansionPanelElement: {
    prototype: HTMLOExpansionPanelElement;
    new (): HTMLOExpansionPanelElement;
  };

  interface HTMLOExpansionPanelsElement extends Components.OExpansionPanels, HTMLStencilElement {}
  var HTMLOExpansionPanelsElement: {
    prototype: HTMLOExpansionPanelsElement;
    new (): HTMLOExpansionPanelsElement;
  };
  interface HTMLElementTagNameMap {
    'o-button': HTMLOButtonElement;
    'o-expansion-panel': HTMLOExpansionPanelElement;
    'o-expansion-panels': HTMLOExpansionPanelsElement;
  }
}

declare namespace LocalJSX {
  interface OButton extends JSXBase.HTMLAttributes<HTMLOButtonElement> {
    /**
    * The text button is bold
    */
    'bold'?: boolean;
    /**
    * The button color
    */
    'color'?: Color;
    /**
    * The button enable status
    */
    'disabled'?: boolean;
    /**
    * The outline style
    */
    'outline'?: boolean;
    /**
    * The button size
    */
    'size'?: PredefinedGlobalSize;
    /**
    * The button type
    */
    'type'?: PredefinedButtonType;
  }
  interface OExpansionPanel extends JSXBase.HTMLAttributes<HTMLOExpansionPanelElement> {
    'disabled'?: boolean;
    'open'?: boolean;
    'value'?: number;
  }
  interface OExpansionPanels extends JSXBase.HTMLAttributes<HTMLOExpansionPanelsElement> {}

  interface IntrinsicElements {
    'o-button': OButton;
    'o-expansion-panel': OExpansionPanel;
    'o-expansion-panels': OExpansionPanels;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


