/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
  PredefinedButtonType,
  PredefinedGlobalSize,
} from './interface';


export namespace Components {
  interface OButton {
    /**
    * The button color
    */
    'color'?: Color;
    /**
    * The button enable status
    */
    'disabled': boolean;
    /**
    * The outline style
    */
    'outline': boolean;
    /**
    * The button size
    */
    'size'?: PredefinedGlobalSize;
    /**
    * The button type
    */
    'type'?: PredefinedButtonType;
  }
}

declare global {


  interface HTMLOButtonElement extends Components.OButton, HTMLStencilElement {}
  var HTMLOButtonElement: {
    prototype: HTMLOButtonElement;
    new (): HTMLOButtonElement;
  };
  interface HTMLElementTagNameMap {
    'o-button': HTMLOButtonElement;
  }
}

declare namespace LocalJSX {
  interface OButton extends JSXBase.HTMLAttributes<HTMLOButtonElement> {
    /**
    * The button color
    */
    'color'?: Color;
    /**
    * The button enable status
    */
    'disabled'?: boolean;
    /**
    * The outline style
    */
    'outline'?: boolean;
    /**
    * The button size
    */
    'size'?: PredefinedGlobalSize;
    /**
    * The button type
    */
    'type'?: PredefinedButtonType;
  }

  interface IntrinsicElements {
    'o-button': OButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


